### PR TITLE
fix markdown table formatting

### PR DESCRIPTION
**Pull request by Commod0re**
humbly I come to you with a patch to fix this markdown table's formatting so it renders correctly

## Summary by CodeRabbit

- **Documentation**
	- Improved the readability of the `client_id` parameter description in the global parameters table by consolidating it into a single line with HTML line breaks.

### CODE REVIEW

**Comment by LukeHagar** [comment]
LOL thanks, I have a ticket open internally to fix this during generation :)

**Comment by LukeHagar** [comment]
This entire repository is generated code, so changes like this will just get overwritten when generation occurs.

**Comment by Commod0re** [comment]
ahh fair enough

**Comment by LukeHagar** [comment]
This [repo](https://github.com/LukeHagar/plex-api-spec), is what everything is generated from. If you have any issues feel free to contribute or raise issues there!

**Comment by LukeHagar** [comment]
This should be fixed globally btw, just removed the new lines from that description

**Comment by LukeHagar** [comment]
just waiting on everything to regenerate

**Pull request closed without merging**
